### ISSUE TITLE
loading JPEGs shows an error

### ISSUE THREAD

**Issue by muzamilmkhan** [tischi/fiji-plugin-plateViewer#3]
Hey Tischi,
Loading JPEGS is certainly much faster but when I zoom our quickly, I get the following error and the images pause or stop to load 
------------
Caused by: java.lang.ClassCastException
java.util.concurrent.ExecutionException: java.lang.ClassCastException
 at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
 at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
 at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:362)
 at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:19)
 at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:409)
 at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:386)
 at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:180)
Caused by: java.lang.ClassCastException
java.util.concurrent.ExecutionException: java.lang.ClassCastException
 at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
 at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
 at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:362)
 at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:19)
 at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:409)
 at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:386)
 at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:180)
Caused by: java.lang.ClassCastException
java.util.concurrent.ExecutionException: java.lang.ClassCastException
 at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
 at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
 at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:362)
 at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:19)
 at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:409)
 at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:386)
 at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:180)
Caused by: java.lang.ClassCastException

---

**Comment by tischi** [comment]
Thanks for the report! And sorry for the late reply!
Did you recently try this again? Is this still happening?

**Comment by muzamilmkhan** [comment]
Hey Tischi,
I think you had solved it at some point while there were other issues then, but couldn’t get back to it actually.

Thanks for following it up
best regards
muzamil
