### ISSUE TITLE
Write multi-resolution Tiff

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-plateViewer#4]
@sbesson @joshmoore @dgault

I am struggling to write proper multi-resolution Tiff files (quoting Sebastien):

> your attached TIFF file is definitely not matching what you expect i.e. it contains 4 IFDs of the same dimension with no sub-resolutions. Also there is no OME metadata i.e. this is a plain (ImageJ) TIFF file as far as I can tell.

This is my current code: https://github.com/tischi/fiji-plugin-plateViewer/blob/master/src/test/java/explore/WriteMultiResolutionTiff.java#L17
Could you help me?

Please see  here for how it currently goes wrong: https://forum.image.sc/t/bio-formats-6-update/21223/14

**Comment by tischi** [comment]
Hi @sbesson 
,
It works better now, however when I try to read the image back in the resolutions seemingly all have the size:
```
Initializing file: /Users/tischer/Documents/fiji-plugin-plateViewer/src/test/resources/PyramidalTiff/image-scale2res4-lzw.ome.tif
  Series count = 1
    Resolution count for series #0 = 4
      Resolution #0 dimensions = 1608 x 1608
      Resolution #1 dimensions = 1608 x 1608
      Resolution #2 dimensions = 1608 x 1608
      Resolution #3 dimensions = 1608 x 1608
```
I am using this code for reading: https://github.com/tischi/fiji-plugin-plateViewer/blob/master/src/test/java/explore/ReadMultiResolutionTiff.java#L14

**Comment by sbesson** [comment]
@tischi agreed about the resolutions size - see the comment put at the bottom of my [PR description](https://github.com/tischi/fiji-plugin-plateViewer/pull/8#issue-273934831).

The issue is also there in the upstream example - see https://github.com/ome/bio-formats-examples/issues/48. I will probably have no capacity to look into that before Wednesday but @melissalinkert or @dgault might have pointers about how to fix the sequence of API calls.

**Comment by tischi** [comment]
@sbesson OK! I overlooked your comment in the PR. I will just wait until I hear from you...

**Comment by tischi** [comment]
@dgault @melissalinkert @sbesson 
Did you guys have a chance to look into it?

**Comment by sbesson** [comment]
@tischi see https://github.com/ome/bio-formats-examples/issues/48#issuecomment-488053831. We are looking into a proper fix for Bio-Formats 6.1. In the interim, can you test setting `writer.setWriteSequentially(true)`?

**Comment by sbesson** [comment]
Update: we just released a milestone with what we believe fixes the issue. Can you update your POM to consume `ome:formats-*:6.1.0-m2` and see if that fixes the issue?

**Comment by tischi** [comment]
I use in my pom:
```
<bioformats.version>6.1.0-m2</bioformats.version>
```

And I am getting this error:
```
16:12:17.325 [main] DEBUG loci.formats.tiff.TiffSaver - Reading IFD from 8 in non-sequential write.
Exception in thread "main" loci.formats.FormatException: Unknown IFD value type ([Ljava.lang.String;): [Ljava.lang.String;@68e5eea7
	at loci.formats.tiff.TiffSaver.writeIFDValue(TiffSaver.java:688)
	at loci.formats.tiff.TiffSaver.writeIFD(TiffSaver.java:527)
	at loci.formats.tiff.TiffSaver.writeIFDStrips(TiffSaver.java:1010)
	at loci.formats.tiff.TiffSaver.writeImageIFD(TiffSaver.java:492)
	at loci.formats.tiff.TiffSaver.writeImage(TiffSaver.java:432)
	at loci.formats.tiff.TiffSaver.writeImage(TiffSaver.java:277)
	at loci.formats.out.TiffWriter.saveBytes(TiffWriter.java:279)
	at loci.formats.out.OMETiffWriter.saveBytes(OMETiffWriter.java:218)
	at loci.formats.out.PyramidOMETiffWriter.saveBytes(PyramidOMETiffWriter.java:89)
	at loci.formats.out.OMETiffWriter.saveBytes(OMETiffWriter.java:208)
	at loci.formats.FormatWriter.saveBytes(FormatWriter.java:131)
	at loci.formats.ImageWriter.saveBytes(ImageWriter.java:252)
	at explore.WriteMultiResolutionTiff.main(WriteMultiResolutionTiff.java:51)
```

**Comment by sbesson** [comment]
Tried to run the compilation but failed with

```
[ERROR] Failed to execute goal on project fiji-plugin-plateViewer: Could not resolve dependencies for project org.scijava:fiji-plugin-plateViewer:jar:0.2.18: Failure to find de.embl.cba:bdv-utils:jar:0.2.14 in https://maven.imagej.net/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of imagej.public has elapsed or updates are forced -> [Help 1]
```

**Comment by tischi** [comment]
Yes, sorry, I really need to get my dev-ops sorted.
I should work now (I tested with Travis).

**Comment by sbesson** [comment]
Thanks. I think I found  the issue. You are appending to an existing file (which is committed under version control). I tested by deleting the file first 

```
sbesson@ls30630:fiji-plugin-plateViewer (master) $ mvn
sbesson@ls30630:fiji-plugin-plateViewer (master) $ rm -rf src/test/resources/PyramidalTiff/image-scale*
sbesson@ls30630:fiji-plugin-plateViewer (master) $  mvn exec:java -Dexec.mainClass="explore.WriteMultiResolutionTiff" -Dexec.classpathScope="test"
```

The code now runs to completion, I can open the generated file and all sub-resolutions look good.

<img width="1552" alt="Screen Shot 2019-05-10 at 18 14 46" src="https://user-images.githubusercontent.com/1355463/57544529-873c5700-734f-11e9-9bf5-93f7834554de.png">
<img width="518" alt="Screen Shot 2019-05-10 at 18 14 18" src="https://user-images.githubusercontent.com/1355463/57544530-886d8400-734f-11e9-8dc2-3cd0a41091ac.png">

**Comment by tischi** [comment]
Fantastic! 
Is there something in `IFormatWriter writer = new ImageWriter();` that I could set to tell it to overwrite rather than append?

**Comment by sbesson** [comment]
I don't think the writer API has such logic but this is something you can achieve separately using the standard `java.io` utility. See https://github.com/openmicroscopy/bioformats/blob/v6.1.0-m2/components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java#L400 as an example on how `bfconvert` implements the file check + deletion.
